name: to_do_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  win32: ^5.5.0
  flutter_native_timezone: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  share_plus: 11.1.0          # اشتراک‌گذاری فایل‌ها
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.3.2
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  linux:
    generate: true
  macos:
    generate: true
  windows:
    generate: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Vaziri
      fonts:
        - asset: assets/fonts/Vaziri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vaziri-Bold.ttf
          weight: 700
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IRANSans-Bold.ttf
          weight: 700




